import { type ModuleIconName } from "@/app/components/module-icon";

export type HouseResident = {
  id: string;
  initials: string;
  name: string;
  room: string;
  unit: string;
  status: Exclude<ResidentStatus, "Alle">;
  tone: ResidentTone;
  period: string;
  lastEntry: string;
  lastEntryAt: string;
  author: string;
  note: string;
  icon: ModuleIconName;
};

export const residents: HouseResident[] = [
  {
    id: "r01",
    initials: "HM",
    name: "Hans Müller",
    room: "Zimmer 207",
    unit: "Wohnbereich 2",
    status: "Aktiv",
    tone: "critical",
    period: "Eintritt 12.03.2024",
    lastEntry: "Neurologische Kontrolle nach Sturz",
    lastEntryAt: "Heute, 08:12",
    author: "Anna Meier",
    note: "Engmaschige Beobachtung bis 14:00 Uhr weiterführen.",
    icon: "alert",
  },
  {
    id: "r02",
    initials: "MK",
    name: "Maria Keller",
    room: "Zimmer 204",
    unit: "Wohnbereich 2",
    status: "Aktiv",
    tone: "attention",
    period: "Eintritt 06.11.2023",
    lastEntry: "Blutzucker vor Frühstück erfasst",
    lastEntryAt: "Heute, 07:42",
    author: "Anna Meier",
    note: "Korrekturschema gemäss Verordnung angewendet.",
    icon: "vitals",
  },
  {
    id: "r03",
    initials: "EM",
    name: "Erika Meier",
    room: "Zimmer 211",
    unit: "Wohnbereich 2",
    status: "Aktiv",
    tone: "attention",
    period: "Eintritt 19.08.2022",
    lastEntry: "Morgenmedikation angepasst",
    lastEntryAt: "Heute, 07:30",
    author: "Nora Baumann",
    note: "Verträglichkeit der neuen Metoprolol-Dosierung beobachten.",
    icon: "med",
  },
  {
    id: "r04",
    initials: "RB",
    name: "Ruth Baumann",
    room: "Zimmer 214",
    unit: "Wohnbereich 2",
    status: "Aktiv",
    tone: "stable",
    period: "Eintritt 24.01.2025",
    lastEntry: "Morgenpflege abgeschlossen",
    lastEntryAt: "Heute, 06:50",
    author: "Nora Baumann",
    note: "Mobilisation mit Rollator sicher, Hautzustand unverändert.",
    icon: "note",
  },
  {
    id: "r05",
    initials: "PA",
    name: "Peter Aebischer",
    room: "Zimmer 115",
    unit: "Wohnbereich 1",
    status: "Aktiv",
    tone: "stable",
    period: "Eintritt 02.05.2025",
    lastEntry: "Trinkprotokoll ergänzt",
    lastEntryAt: "Heute, 07:10",
    author: "Lea Frei",
    note: "180 ml zum Frühstück getrunken, weiter motivieren.",
    icon: "nutrition",
  },
  {
    id: "r06",
    initials: "AS",
    name: "Anna Schmid",
    room: "Zimmer 118",
    unit: "Wohnbereich 1",
    status: "Aktiv",
    tone: "stable",
    period: "Eintritt 17.02.2026",
    lastEntry: "Mobilisation dokumentiert",
    lastEntryAt: "Gestern, 19:40",
    author: "Lea Frei",
    note: "Selbstständig mit Gehstock auf dem Wohnbereich.",
    icon: "tasks",
  },
  {
    id: "r07",
    initials: "WB",
    name: "Walter Brunner",
    room: "Zimmer 306",
    unit: "Wohnbereich 3",
    status: "Aktiv",
    tone: "info",
    period: "Eintritt 09.09.2026",
    lastEntry: "Eintrittsassessment abgeschlossen",
    lastEntryAt: "Gestern, 16:25",
    author: "Nora Baumann",
    note: "Pflegeplanung zur interprofessionellen Freigabe vorbereitet.",
    icon: "assess",
  },
  {
    id: "r08",
    initials: "LF",
    name: "Lydia Frei",
    room: "Zimmer 309",
    unit: "Wohnbereich 3",
    status: "Aktiv",
    tone: "stable",
    period: "Eintritt 14.06.2021",
    lastEntry: "Schmerzassessment ohne Auffälligkeit",
    lastEntryAt: "Gestern, 14:10",
    author: "Anna Meier",
    note: "NRS 0 in Ruhe und bei Mobilisation.",
    icon: "assess",
  },
  {
    id: "r09",
    initials: "BK",
    name: "Bernhard Koch",
    room: "Zimmer 012",
    unit: "Pflegewohngruppe",
    status: "Aktiv",
    tone: "attention",
    period: "Eintritt 30.10.2024",
    lastEntry: "Unruhe am Nachmittag beobachtet",
    lastEntryAt: "Gestern, 17:45",
    author: "Sven Keller",
    note: "Biografieorientierte Begleitung wirksam, keine Bedarfsmedikation.",
    icon: "note",
  },
  {
    id: "r10",
    initials: "ZG",
    name: "Zora Graf",
    room: "Zimmer 015",
    unit: "Pflegewohngruppe",
    status: "Aktiv",
    tone: "stable",
    period: "Eintritt 11.04.2023",
    lastEntry: "Essbegleitung dokumentiert",
    lastEntryAt: "Gestern, 12:35",
    author: "Sven Keller",
    note: "Dreiviertel der Mahlzeit selbstständig eingenommen.",
    icon: "nutrition",
  },
  {
    id: "r11",
    initials: "ES",
    name: "Elisabeth Sommer",
    room: "Neu: Zimmer 312",
    unit: "Wohnbereich 3",
    status: "Verlegt",
    tone: "info",
    period: "Verlegt am 08.09.2026",
    lastEntry: "Interne Verlegung abgeschlossen",
    lastEntryAt: "8. Sept., 10:15",
    author: "Lea Frei",
    note: "Von Wohnbereich 1 nach Wohnbereich 3 verlegt; Übergabe vollständig.",
    icon: "handover",
  },
  {
    id: "r12",
    initials: "KH",
    name: "Kurt Hofer",
    room: "Ehem. Zimmer 108",
    unit: "Wohnbereich 1",
    status: "Ausgetreten",
    tone: "archived",
    period: "Austritt 31.08.2026",
    lastEntry: "Austrittsbericht freigegeben",
    lastEntryAt: "31. Aug., 15:20",
    author: "Anna Meier",
    note: "Rückkehr nach Hause mit Spitex-Anschluss; Akte vollständig archiviert.",
    icon: "docs",
  },
  {
    id: "r13",
    initials: "MG",
    name: "Marlies Gasser",
    room: "Ehem. Zimmer 303",
    unit: "Wohnbereich 3",
    status: "Ausgetreten",
    tone: "archived",
    period: "Austritt 14.08.2026",
    lastEntry: "Übertrittsdokumentation versendet",
    lastEntryAt: "14. Aug., 11:05",
    author: "Nora Baumann",
    note: "Übertritt in Rehabilitationsklinik, Unterlagen vollständig übermittelt.",
    icon: "docs",
  },
  {
    id: "r14",
    initials: "HF",
    name: "Heidi Furrer",
    room: "Ehem. Zimmer 009",
    unit: "Pflegewohngruppe",
    status: "Ausgetreten",
    tone: "archived",
    period: "Austritt 02.07.2026",
    lastEntry: "Austrittsmedikation abgeglichen",
    lastEntryAt: "2. Juli, 09:30",
    author: "Lea Frei",
    note: "Übertritt in betreutes Wohnen; Abschlusskontrolle erfolgt.",
    icon: "med",
  },
  {
    id: "r15",
    initials: "AR",
    name: "Alfred Roth",
    room: "Ehem. Zimmer 202",
    unit: "Wohnbereich 2",
    status: "Verstorben",
    tone: "archived",
    period: "Verstorben 22.08.2026",
    lastEntry: "Pflegeabschluss dokumentiert",
    lastEntryAt: "22. Aug., 06:40",
    author: "Anna Meier",
    note: "Abschied und administrative Nachbearbeitung abgeschlossen; Akte geschützt archiviert.",
    icon: "docs",
  },
  {
    id: "r16",
    initials: "JS",
    name: "Johanna Suter",
    room: "Ehem. Zimmer 305",
    unit: "Wohnbereich 3",
    status: "Verstorben",
    tone: "archived",
    period: "Verstorben 18.06.2026",
    lastEntry: "Abschlussgespräch dokumentiert",
    lastEntryAt: "19. Juni, 14:00",
    author: "Nora Baumann",
    note: "Abschlussgespräch mit Angehörigen erfolgt; Akte geschützt archiviert.",
    icon: "docs",
  },
];

export type ResidentStatus = "Alle" | "Aktiv" | "Verlegt" | "Ausgetreten" | "Verstorben";

export type ResidentTone = "critical" | "attention" | "info" | "stable" | "archived";
