import type {
  CareDomain,
  HistoryEntry,
  ResidentDocument,
  ResidentRecordData,
  DocumentationEntry,
} from "./resident-record-data";

export const careDomains: CareDomain[] = [
  {
    id: "mobility",
    label: "Mobilität & Bewegung",
    status: "attention",
    statusLabel: "Beobachten",
    summary: "Mobilisation mit Rollator und Begleitung. Erhöhtes Sturzrisiko bei Lagewechseln und in der Nacht.",
    goal: "Sichere Mobilität im Wohnbereich erhalten und weitere Sturzereignisse vermeiden.",
    measures: [
      "Transfers mit verbaler Anleitung begleiten",
      "Rollator vor jedem Aufstehen bereitstellen",
      "Sturzprophylaxe und neurologische Kontrollen fortführen",
    ],
  },
  {
    id: "nutrition",
    label: "Ernährung & Flüssigkeit",
    status: "stable",
    statusLabel: "Stabil",
    summary: "Normalkost, selbstständige Nahrungsaufnahme. Trinkmenge im vereinbarten Zielbereich.",
    goal: "Tägliche Flüssigkeitszufuhr von mindestens 1,5 Litern sicherstellen.",
    measures: [
      "Getränke sichtbar und erreichbar bereitstellen",
      "Trinkmenge pro Schicht dokumentieren",
      "Gewicht wöchentlich kontrollieren",
    ],
  },
  {
    id: "cognition",
    label: "Kognition & Orientierung",
    status: "info",
    statusLabel: "Unterstützung",
    summary: "Zeitlich teilweise desorientiert, örtliche und persönliche Orientierung erhalten.",
    goal: "Orientierung und Selbstbestimmung im Tagesablauf bestmöglich unterstützen.",
    measures: [
      "Tagesstruktur sichtbar kommunizieren",
      "Kurze und eindeutige Informationen geben",
      "Biografiebezogene Aktivierung anbieten",
    ],
  },
  {
    id: "skin",
    label: "Haut & Wunden",
    status: "stable",
    statusLabel: "Stabil",
    summary: "Haut intakt, aktuell keine offenen Wunden. Trockene Haut an beiden Unterschenkeln.",
    goal: "Intakte Haut erhalten und Hauttrockenheit reduzieren.",
    measures: [
      "Hautbeobachtung während der Körperpflege",
      "Unterschenkel morgens und abends eincremen",
      "Druckstellen unmittelbar dokumentieren",
    ],
  },
  {
    id: "elimination",
    label: "Ausscheidung",
    status: "stable",
    statusLabel: "Stabil",
    summary: "Kontinente Ausscheidung mit selbstständiger Toilettennutzung am Tag.",
    goal: "Selbstständige Toilettennutzung und regelmäßige Ausscheidung erhalten.",
    measures: [
      "Toilettengänge nach Bedarf begleiten",
      "Ausscheidungsverhalten beobachten",
      "Veränderungen im Verlauf dokumentieren",
    ],
  },
  {
    id: "sleep",
    label: "Ruhe & Schlaf",
    status: "attention",
    statusLabel: "Beobachten",
    summary: "Unterbrochener Nachtschlaf mit zwei bis drei Wachphasen und nächtlichem Bewegungsdrang.",
    goal: "Erholsame Ruhephasen fördern und nächtliche Sturzgefährdung reduzieren.",
    measures: [
      "Abendritual und Ruhezeiten einhalten",
      "Nachtlicht und Rufanlage kontrollieren",
      "Schlafverhalten im Nachtbericht festhalten",
    ],
  },
];

export const historyEntries: HistoryEntry[] = [
  {
    id: "h1",
    date: "Heute · 10. September 2026",
    time: "08:10",
    category: "Pflege",
    title: "Hautbeobachtung ergänzt",
    description: "Rötung an der rechten Schulter dokumentiert und Druckentlastung für die laufende Schicht geplant.",
    author: "Anna Meier · Pflegefachfrau HF",
    tone: "attention",
    documentationId: "observation",
  },
  {
    id: "h2",
    date: "Heute · 10. September 2026",
    time: "07:55",
    category: "Pflege",
    title: "Wundversorgung durchgeführt",
    description: "Hautläsion am linken Unterarm gereinigt und mit trockener Wundauflage versorgt.",
    author: "Lea Frei · Fachfrau Gesundheit",
    tone: "critical",
  },
  {
    id: "h3",
    date: "Heute · 10. September 2026",
    time: "07:42",
    category: "Vitalwerte",
    title: "Vitalwerte erfasst",
    description: "Blutdruck 132/78 mmHg · Puls 72/min · Temperatur 36,7 °C.",
    author: "Anna Meier · Pflegefachfrau HF",
    tone: "stable",
    documentationId: "vitals",
  },
  {
    id: "h4",
    date: "Heute · 10. September 2026",
    time: "07:30",
    category: "Medikation",
    title: "Morgenmedikation verabreicht",
    description: "Vier von sechs geplanten Medikationen gemäss aktuellem Medikamentenplan abgegeben.",
    author: "Lea Frei · Fachfrau Gesundheit",
    tone: "info",
    documentationId: "medication",
  },
  {
    id: "h5",
    date: "Gestern · 9. September 2026",
    time: "16:20",
    category: "Termine",
    title: "Orthopädische Verlaufskontrolle",
    description: "Heilungsverlauf der proximalen Tibiafraktur regelrecht; Teilbelastung bleibt bestehen.",
    author: "Dr. med. Martin Weber",
    tone: "info",
  },
  {
    id: "h6",
    date: "Gestern · 9. September 2026",
    time: "14:05",
    category: "Pflege",
    title: "Mobilisation begleitet",
    description: "Transfer mit Rollator sicher durchgeführt, keine Schwindelangabe bei Lagewechsel.",
    author: "Anna Meier · Pflegefachfrau HF",
    tone: "stable",
  },
];

export const residentDocuments: ResidentDocument[] = [
  {
    id: "d1",
    title: "Ärztlicher Verlaufsbericht September",
    category: "Arztberichte",
    fileType: "PDF",
    size: "1,8 MB",
    updated: "Heute, 08:35",
    owner: "Dr. Martin Weber",
    status: "Neu",
  },
  {
    id: "d2",
    title: "Pflegeplanung und Maßnahmen",
    category: "Pflege",
    fileType: "PDF",
    size: "840 KB",
    updated: "Gestern, 17:10",
    owner: "Anna Meier",
    status: "Aktuell",
  },
  {
    id: "d3",
    title: "Aktueller Medikamentenplan",
    category: "Medikation",
    fileType: "PDF",
    size: "420 KB",
    updated: "9. September 2026",
    owner: "Dr. Martin Weber",
    status: "Aktuell",
  },
  {
    id: "d4",
    title: "Einwilligung zur Datenfreigabe",
    category: "Administration",
    fileType: "PDF",
    size: "265 KB",
    updated: "8. September 2026",
    owner: "Administration",
    status: "Unterschrift offen",
  },
  {
    id: "d5",
    title: "Wunddokumentation linker Unterarm",
    category: "Pflege",
    fileType: "PDF",
    size: "3,2 MB",
    updated: "7. September 2026",
    owner: "Lea Frei",
    status: "Aktuell",
  },
  {
    id: "d6",
    title: "Austrittsbericht Akutspital",
    category: "Arztberichte",
    fileType: "PDF",
    size: "2,4 MB",
    updated: "14. August 2026",
    owner: "Stadtspital Zürich",
    status: "Aktuell",
  },
];

export function getDocumentationEntries(resident: ResidentRecordData): DocumentationEntry[] {
  return [
    {
      id: "observation",
      time: "08:00",
      title: "Pflegebeobachtung aktualisiert",
      text: resident.note,
      author: "Anna Meier · Pflegefachfrau HF",
      category: "Pflegebeobachtung",
    },
    {
      id: "vitals",
      time: "07:42",
      title: "Vitalwerte erfasst",
      text: "Blutdruck 132/78 mmHg · Puls 72/min · Temperatur 36,7 °C",
      author: "Anna Meier · Pflegefachfrau HF",
      category: "Vitalwerte",
    },
    {
      id: "medication",
      time: "07:30",
      title: "Medikation verabreicht",
      text: "Morgenmedikation gemäss aktuellem Medikamentenplan.",
      author: "Lea Frei · Fachfrau Gesundheit",
      category: "Medikation",
    },
    {
      id: "handover",
      time: "06:55",
      title: "Dienstübergabe übernommen",
      text: "Nachtverlauf geprüft, offene Beobachtungen in den Dienstplan übernommen.",
      author: "Systemeintrag",
      category: "Übergabe",
    },
  ];
}
