// Auskunft und Datenexport je Person (Server und Oberfläche): alle gespeicherten Daten einer Akte, nach Bereichen.
import { ABSENCE_KINDS } from "@/lib/billing-shared";
import { DIAGNOSIS_KINDS, DIAGNOSIS_STATUSES } from "@/lib/diagnoses-shared";
import { VACCINATION_PLACES } from "@/lib/vaccinations-shared";
import { BELONGING_KINDS } from "@/lib/belongings-shared";
import { CONSENT_DECISIONS } from "@/lib/consents-shared";
import { TRANSPORT_LABELS } from "@/lib/resident-appointments";
import { DAY_PARTS, PROOF_OUTCOMES } from "@/lib/intervention-proofs-shared";
import { FEEDBACK_CHANNELS, FEEDBACK_KINDS, FEEDBACK_SOURCES, FEEDBACK_STATUSES } from "@/lib/feedback-shared";

const DAY_PART_LABELS = Object.fromEntries(Object.entries(DAY_PARTS).map(([key, part]) => [key, part.label]));

export type ExportSection = { key: string; title: string; rows: Array<Record<string, unknown>> };

export type ResidentExport = {
  format: "carecore-auskunft";
  version: 1;
  generatedAt: string;
  organization: string;
  resident: { id: string; name: string; birthDate: string | null };
  requestedBy: string;
  generatedBy: string;
  // Namen der Mitarbeitenden zu den Kennungen in den Daten (Verfasser, geändert von …).
  staff: Record<string, string>;
  sections: ExportSection[];
  // Was nicht enthalten ist (z. B. Dateien) und wie es zu erhalten ist.
  notes: string[];
};

// Grundlagen (beim Bau an der Quelle geprüft, Stand 10/2026): CH DSG Art. 25 (Auskunft, kostenlos, verständlich,
// in der Regel innert 30 Tagen) und Art. 28 (Herausgabe in einem gängigen elektronischen Format); DE/AT DSGVO Art. 15
// (Auskunft und Kopie) und Art. 20 (strukturiert, gängig, maschinenlesbar), Frist nach Art. 12 Abs. 3 ein Monat.
export const EXPORT_LEGAL_NOTE =
  "Auskunft nach DSG Art. 25 und 28 (Schweiz) bzw. DSGVO Art. 15 und 20 (Deutschland, Österreich). Die Einrichtung prüft vor der Herausgabe die Identität und Berechtigung der anfragenden Person sowie allfällige Einschränkungen.";

// Lesbare Fassung: interne Angaben, die nur in der Datei stehen (Verweise, Speicherorte, Technik).
export const EXPORT_HIDDEN_COLUMNS = new Set([
  "id",
  "organization_id",
  "resident_id",
  "rate_id",
  "account_id",
  "activity_id",
  "administration_id",
  "amended_from_id",
  "assessment_id",
  "care_goal_id",
  "care_plan_id",
  "catalog_id",
  "desired_care_unit_id",
  "entry_id",
  "documentation_entry_id",
  "file_id",
  "follow_up_task_id",
  "intervention_id",
  "measure_id",
  "medication_id",
  "medication_order_id",
  "movement_id",
  "order_id",
  "outbreak_id",
  "previous_id",
  "product_id",
  "quality_event_id",
  "resident_supply_id",
  "resolved_by_portal_account_id",
  "response_entry_id",
  "room_id",
  "saved_entity_id",
  "saved_entity_type",
  "shift_id",
  "source_id",
  "stock_id",
  "thread_id",
  "wound_id",
  "storage_key",
  "photo_storage_key",
  "photo_base64",
  "photo_mime_type",
  "mime_type",
  "user_agent",
  "model",
  "prompt",
  "body_x",
  "body_y",
  "body_z",
  "metadata",
  "data",
  "answers",
  "portal_read_at",
  "staff_read_at",
  "effect_reminded_at",
  "reminded_at",
  "updated_at",
  "updated_by",
  "version",
]);

// Deutsche Bezeichnungen der Spalten, die das Änderungsprotokoll nicht kennt.
export const EXPORT_COLUMN_LABELS: Record<string, string> = {
  acknowledged_at: "Bestätigt am",
  acknowledged_by: "Bestätigt von",
  action: "Vorgang",
  administered_at: "Gegeben am",
  administered_by: "Gegeben von",
  admission_reason: "Eintrittsgrund",
  approved_at: "Freigegeben am",
  approved_by: "Freigegeben von",
  archive_reason: "Grund der Archivierung",
  archived_at: "Archiviert am",
  archived_by: "Archiviert von",
  assessment_type: "Art der Einschätzung",
  assessor_user_id: "Eingeschätzt von",
  assistance: "Unterstützung",
  amount_cents: "Betrag (Rappen bzw. Cent)",
  author_user_id: "Verfasst von",
  booked_on: "Gebucht am",
  batch_number: "Charge",
  beverage: "Getränk",
  body: "Text",
  cancelled_at: "Storniert am",
  cancelled_by: "Storniert von",
  caption: "Beschriftung",
  care_interval_days: "Versorgungsintervall (Tage)",
  care_level: "Pflegestufe",
  change_note: "Änderungsvermerk",
  closed_at: "Abgeschlossen am",
  closed_reason: "Grund des Abschlusses",
  completed_at: "Erledigt am",
  completed_by: "Erledigt von",
  completion_note: "Vermerk zur Erledigung",
  consent_confirmed: "Einwilligung bestätigt",
  consumed_at: "Getrunken am",
  contact_email: "E-Mail der Kontaktperson",
  contact_name: "Kontaktperson",
  contact_phone: "Telefon der Kontaktperson",
  content: "Inhalt",
  party: "Von bzw. an",
  purpose: "Zweck",
  receipt: "Beleg-Nr.",
  counted_by: "Gezählt von",
  counted_quantity: "Gezählte Menge",
  created_at: "Erfasst am",
  created_by: "Erfasst von",
  current_quantity: "Aktuelle Menge",
  daily_calorie_target: "Tagesziel Kalorien",
  daily_fluid_target_ml: "Tagesziel Trinkmenge (ml)",
  daily_routines: "Tagesablauf",
  date_of_birth: "Geburtsdatum",
  deceased_on: "Verstorben am",
  delete_reason: "Grund der Löschung",
  deleted_at: "Gelöscht am",
  deleted_by: "Gelöscht von",
  delta: "Veränderung",
  depth_cm: "Tiefe (cm)",
  details: "Einzelheiten",
  discharged_on: "Ausgetreten am",
  discovered_at: "Entdeckt am",
  document_on_completion: "Bei Erledigung dokumentieren",
  dosage: "Dosierung",
  eaten_at: "Gegessen am",
  effect_check_due_at: "Wirkungskontrolle fällig am",
  effect_checked_at: "Wirkung geprüft am",
  effect_checked_by: "Wirkung geprüft von",
  effect_note: "Vermerk zur Wirkung",
  effect_result: "Wirkung",
  end_note: "Vermerk zum Ende",
  end_reason: "Grund des Endes",
  ended_at: "Beendet am",
  ended_by: "Beendet von",
  ends_at: "Endet am",
  entered_by: "Eingetragen von",
  entry_type: "Art des Eintrags",
  escalated_at: "Eskaliert am",
  escalated_by: "Eskaliert von",
  escalation_reason: "Grund der Eskalation",
  evaluated_at: "Ausgewertet am",
  evaluation_note: "Auswertung",
  expected_on: "Erwartet am",
  expected_quantity: "Erwartete Menge",
  expires_on: "Verfällt am",
  external_number: "Externe Nummer",
  exudate: "Exsudat",
  fluid_limit_ml: "Trinkmenge höchstens (ml)",
  gp_name: "Hausärztin / Hausarzt",
  gp_phone: "Telefon Hausarztpraxis",
  gp_practice: "Hausarztpraxis",
  height: "Grösse",
  immediate_action: "Sofortmassnahme",
  important_people: "Wichtige Menschen",
  infection_signs: "Infektzeichen",
  insurance_number: "Versichertennummer",
  insurer: "Versicherung",
  is_emergency_contact: "Notfallkontakt",
  is_primary: "Hauptkontakt",
  item_name: "Artikel",
  label: "Bezeichnung",
  last_message_at: "Letzte Nachricht am",
  length_cm: "Länge (cm)",
  life_story: "Lebensgeschichte",
  lower_bound: "Untere Grenze",
  marital_status: "Zivilstand",
  master_data_checked_at: "Stammdaten geprüft am",
  master_data_checked_by: "Stammdaten geprüft von",
  materials: "Material",
  meal_rhythm: "Mahlzeitenrhythmus",
  measured_at: "Gemessen am",
  measured_by: "Gemessen von",
  medication: "Medikament",
  minimum_quantity: "Mindestmenge",
  next_review_on: "Nächste Überprüfung am",
  observed_at: "Beobachtet am",
  occurred_at: "Zeitpunkt",
  odor: "Geruch",
  owner_user_id: "Verantwortlich",
  pain_score: "Schmerz (0–10)",
  performed_by: "Durchgeführt von",
  pharmacy: "Apotheke",
  pharmacy_note: "Vermerk der Apotheke",
  photo_updated_at: "Foto geändert am",
  photos: "Fotos",
  physician: "Ärztin / Arzt",
  preferences: "Vorlieben",
  preferred_name: "Rufname",
  prescribed_by: "Verordnet von",
  primary_care_user_id: "Bezugspflegeperson",
  prn_instructions: "Anweisung für die Reserve",
  recorded_at: "Erfasst am",
  recorded_by: "Erfasst von",
  relationship: "Beziehung",
  religion: "Religion",
  reported_by: "Gemeldet von",
  resolved_at: "Erledigt am",
  resolved_by: "Erledigt von",
  responsible_role: "Zuständige Rolle",
  responsible_user_id: "Zuständig",
  resuscitation_decided_on: "Reanimationsstatus festgelegt am",
  resuscitation_source: "Grundlage Reanimationsstatus",
  resuscitation_status: "Reanimationsstatus",
  reviewed_at: "Überprüft am",
  reviewed_by: "Überprüft von",
  revoked_at: "Widerrufen am",
  revoked_by: "Widerrufen von",
  risk_flags: "Risiken",
  risk_level: "Risikostufe",
  scheduled_at: "Geplant für",
  secondary_value: "Zweiter Wert",
  sender: "Absender",
  sender_user_id: "Gesendet von",
  sensitive_topics: "Heikle Themen",
  social_security_number: "AHV- bzw. Sozialversicherungsnummer",
  started_at: "Begonnen am",
  started_by: "Begonnen von",
  status_note: "Vermerk zum Status",
  stay_type: "Art des Aufenthalts",
  storage_location: "Aufbewahrungsort",
  strengths: "Stärken",
  subject: "Betreff",
  summary: "Zusammenfassung",
  surrounding_skin: "Umgebende Haut",
  taken_at: "Aufgenommen am",
  target_quantity: "Sollmenge",
  team_visible: "Für das Team sichtbar",
  tissue: "Gewebe",
  treatment: "Behandlung",
  treatment_plan: "Behandlungsplan",
  upper_bound: "Obere Grenze",
  uploaded_by: "Hochgeladen von",
  visibility: "Sichtbarkeit",
  width: "Breite",
  width_cm: "Breite (cm)",
  witness_user_id: "Zweitunterschrift von",
  wound_edge: "Wundrand",
  evacuation_mobility: "Mobilität im Notfall",
  evacuation_note: "Hinweise für den Notfall",
  icd_code: "ICD-10-Code",
  marking: "Kennzeichnung",
  topic: "Thema",
  decision: "Entscheid",
  decided_by: "Entschieden von",
  decided_on: "Datum des Entscheids",
  revoked_on: "Widerrufen am",
  revoke_note: "Bemerkung zum Widerruf",
  location: "Standort",
  removed_at: "Nicht mehr vorhanden seit",
  removed_by: "Vermerkt von",
  removed_reason: "Grund",
  given_on: "Geimpft am",
  target: "Impfung gegen",
  vaccine: "Präparat",
  lot: "Charge",
  given_by: "Geimpft von",
  since_on: "Seit",
  resolved_on: "Abgeschlossen am",
  // Wünsche für die letzte Lebensphase und Ablauf nach dem Todesfall.
  place: "Ort",
  companionship: "Begleitung",
  spiritual: "Religiöse oder spirituelle Wünsche",
  funeral: "Bestattung",
  notify: "Wer informiert werden soll",
  other_wishes: "Weitere Wünsche",
  discussed_with: "Besprochen mit",
  discussed_on: "Besprochen am",
  done_at: "Erledigt am",
  done_by: "Erledigt von",
  // Zusatzangaben der Auskunft selbst.
  art: "Art",
  medication_name: "Präparat",
  medication_strength: "Stärke",
  activity_title: "Angebot",
  activity_starts_at: "Angebot am",
  account_name: "Portal-Zugang",
  account_kind: "Art des Zugangs",
  entity_type: "Bereich",
  actor_user_id: "Durch",
  before_data: "Vorher",
  after_data: "Nachher",
  outside: "Ausser Haus",
  transport: "Transport",
  transport_note: "Transport-Details",
  pickup_at: "Abholung",
  escort: "Begleitung",
  documents: "Mitzugebende Unterlagen",
  departed_at: "Abgefahren am",
  departed_by: "Abfahrt vermerkt von",
  returned_at: "Zurück am",
  returned_by: "Rückkehr vermerkt von",
  answered_by: "Beantwortet von",
  closed_by: "Abgeschlossen von",
  day_parts: "Nachweis je Tageszeit",
  proof_date: "Nachgewiesen für den Tag",
  day_part: "Tageszeit",
  ends_on: "Letzter Tag",
  entry: "Eintrag",
  rate_name: "Taxe",
  addition: "Adresszusatz",
  building: "Hausnummer",
  calculation: "Berechnung des Monats",
  creditor: "Rechnungssteller",
  currency: "Währung",
  issued_on: "Rechnungsdatum",
  lines: "Positionen",
  month: "Monat",
  number: "Rechnungsnummer",
  recipient: "Rechnungsempfänger",
  reference: "Zahlungsreferenz",
  street: "Strasse",
  total_cents: "Total (Rappen bzw. Cent)",
  zip: "Postleitzahl",
};

// Häufige technische Werte in lesbarer Form.
// Werte, die je Bereich etwas anderes bedeuten (z. B. Status „resolved“ einer Diagnose: abgeschlossen).
export const EXPORT_SECTION_VALUE_LABELS: Record<string, Record<string, Record<string, string>>> = {
  diagnoses: { status: DIAGNOSIS_STATUSES, kind: DIAGNOSIS_KINDS },
  vaccinations: { place: VACCINATION_PLACES },
  belongings: { kind: BELONGING_KINDS },
  consents: { decision: CONSENT_DECISIONS },
  appointments: { transport: TRANSPORT_LABELS },
  intervention_proofs: { outcome: PROOF_OUTCOMES, day_part: DAY_PART_LABELS },
  billing: { kind: ABSENCE_KINDS },
  feedback: { kind: FEEDBACK_KINDS, source: FEEDBACK_SOURCES, channel: FEEDBACK_CHANNELS, status: FEEDBACK_STATUSES },
};

export const EXPORT_VALUE_LABELS: Record<string, string> = {
  care_team: "Pflegeteam",
  permanent: "Daueraufenthalt",
  temporary: "Ferien- bzw. Kurzaufenthalt",
  independent: "Geht selbständig",
  assisted: "Geht mit Hilfsmittel oder Begleitung",
  wheelchair: "Rollstuhl",
  bedridden: "Bettlägerig – Transport liegend",
  deposit: "Einzahlung",
  payout: "Auszahlung",
  expense: "Ausgabe",
  true: "ja",
  false: "nein",
};
