import type { CountryCode } from "@/lib/country";

// Versicherungen zur Auswahl in der Akte, je Land der Einrichtung. Die Administration passt die Liste an
// (Konfiguration › Versicherungen); ohne eigene Liste gilt diese Vorgabe.
// Schweiz: zugelassene Krankenversicherer nach dem Verzeichnis des BAG, Stand 1. Januar 2026.
// Deutschland: gesetzliche Kranken- und Pflegekassen (Stand 2026) sowie private Krankenversicherer.
// Österreich: Träger der sozialen Krankenversicherung sowie private Krankenversicherer.
export const DEFAULT_INSURERS: Record<CountryCode, string[]> = {
  CH: [
    "Agrisano",
    "AMB Assurances",
    "Aquilana",
    "Assura",
    "Atupri",
    "Avenir",
    "CONCORDIA",
    "CSS",
    "curaulta",
    "EGK-Gesundheitskasse",
    "Galenos",
    "Glarner Krankenversicherung",
    "Helsana",
    "Krankenkasse Birchmeier",
    "Krankenkasse Luzerner Hinterland",
    "Krankenkasse Steffisburg",
    "Krankenkasse Visperterminen",
    "Krankenkasse Wädenswil",
    "Kranken- und Unfallkasse Einsiedeln",
    "Caisse-maladie de la Vallée d'Entremont",
    "KPT",
    "Mutuel Krankenversicherung (Groupe Mutuel)",
    "ÖKK",
    "Philos",
    "rhenusana",
    "sana24",
    "Sanitas",
    "SLKK",
    "sodalis",
    "Sumiswalder Krankenkasse",
    "SWICA",
    "Sympany",
    "Visana",
    "vita surselva",
  ],
  DE: [
    "AOK Baden-Württemberg",
    "AOK Bayern",
    "AOK Bremen/Bremerhaven",
    "AOK Hessen",
    "AOK Niedersachsen",
    "AOK Nordost",
    "AOK NordWest",
    "AOK PLUS",
    "AOK Rheinland-Pfalz/Saarland",
    "AOK Rheinland/Hamburg",
    "AOK Sachsen-Anhalt",
    "BARMER",
    "DAK-Gesundheit",
    "HEK – Hanseatische Krankenkasse",
    "hkk Krankenkasse",
    "KKH Kaufmännische Krankenkasse",
    "Techniker Krankenkasse (TK)",
    "IKK classic",
    "IKK gesund plus",
    "IKK – Die Innovationskasse",
    "IKK Südwest",
    "BIG direkt gesund",
    "Knappschaft",
    "SVLFG (Landwirtschaftliche Krankenkasse)",
    "Audi BKK",
    "BAHN-BKK",
    "BERGISCHE KRANKENKASSE",
    "Bertelsmann BKK",
    "BKK Akzo Nobel Bayern",
    "BKK Diakonie",
    "BKK Dürkopp Adler",
    "BKK EWE",
    "BKK exklusiv",
    "BKK Faber-Castell & Partner",
    "BKK firmus",
    "BKK Gildemeister Seidensticker",
    "BKK Groz-Beckert",
    "BKK Herkules",
    "BKK Linde",
    "BKK Melitta HMR",
    "BKK mkk – meine krankenkasse",
    "BKK Pfalz",
    "BKK ProVita",
    "BKK Public",
    "BKK Scheufelen",
    "BKK VerbundPlus",
    "BKK Werra-Meissner",
    "BKK Wirtschaft & Finanzen",
    "BKK24",
    "BMW BKK",
    "Bosch BKK",
    "Continentale Betriebskrankenkasse",
    "Debeka BKK",
    "energie-Betriebskrankenkasse",
    "Heimat Krankenkasse",
    "Mercedes-Benz BKK",
    "Merck BKK",
    "Mobil Krankenkasse",
    "Novitas BKK",
    "pronova BKK",
    "R+V Betriebskrankenkasse",
    "Salus BKK",
    "SBK Siemens-Betriebskrankenkasse",
    "SKD BKK",
    "TUI BKK",
    "VIACTIV Krankenkasse",
    "Allianz Private Krankenversicherung",
    "ARAG Krankenversicherung",
    "AXA Krankenversicherung",
    "Barmenia Krankenversicherung",
    "Central Krankenversicherung",
    "Continentale Krankenversicherung",
    "Debeka Krankenversicherung",
    "DKV Deutsche Krankenversicherung",
    "Gothaer Krankenversicherung",
    "HALLESCHE Krankenversicherung",
    "HanseMerkur Krankenversicherung",
    "HUK-COBURG Krankenversicherung",
    "INTER Krankenversicherung",
    "Landeskrankenhilfe (LKH)",
    "LVM Krankenversicherung",
    "Münchener Verein Krankenversicherung",
    "NÜRNBERGER Krankenversicherung",
    "R+V Krankenversicherung",
    "SIGNAL IDUNA Krankenversicherung",
    "Süddeutsche Krankenversicherung (SDK)",
    "Union Krankenversicherung (UKV)",
    "uniVersa Krankenversicherung",
    "Württembergische Krankenversicherung",
  ],
  AT: [
    "Österreichische Gesundheitskasse (ÖGK)",
    "Versicherungsanstalt öffentlich Bediensteter, Eisenbahnen und Bergbau (BVAEB)",
    "Sozialversicherungsanstalt der Selbständigen (SVS)",
    "Krankenfürsorgeanstalt der Bediensteten der Stadt Wien (KFA Wien)",
    "Allianz Elementar",
    "DONAU Versicherung",
    "Generali Versicherung",
    "Merkur Versicherung",
    "Muki Versicherung",
    "UNIQA Österreich",
    "Wiener Städtische Versicherung",
  ],
};

export const INSURERS_MAX = 300;

export type InsurerList = { country: CountryCode; insurers: string[]; custom: boolean };
